language: python
env:
  global:
    - version=$(<VERSION)
services:
  - docker
install:
  - pip install -r requirements.txt
script: true
before_deploy:
  - docker build --tag z0r3f/wallbot-docker:latest .
deploy:
  provider: script
  script: >-
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
      docker build --tag z0r3f/wallbot-docker:latest . &&
      docker images &&
      docker tag z0r3f/wallbot-docker:latest z0r3f/wallbot-docker:$version &&
      docker push z0r3f/wallbot-docker:latest  &&
      docker push z0r3f/wallbot-docker:$version
  on:
    branch: master


